version: '2'
catalog:
  name: Rancher Machine Driver Development
  version: v1.0.0
services:
  uidbuilder:
    scale: 1
    start_on_create: true
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: rmd.rancher.jp2.kudamono.info
        path: ''
        priority: 1
        protocol: http
        service: provider
        source_port: 80
        target_port: 80
      - hostname: test.rancher.jp2.kudamono.info
        path: ''
        priority: 2
        protocol: http
        service: provider
        source_port: 80
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  provider:
    scale: 1
    start_on_create: true
  dmdbuilder:
    scale: 1
    start_on_create: true
  rancherserver:
    scale: 1
    start_on_create: true
